rev_types = dsp3.get_rev_types();

%%

rev_t = 'orig';
bands = dsp3.get_bands( 'map' );

for i = 2
  
base_subdir = '';
  
if ( i == 1 )
  epoch = 'targon';
  mask_inputs = {@find, 'cued'};
  t_window = [0, 250];
else
  epoch = 'targacq';
  mask_inputs = {@find, 'choice'};
  t_window = [-250, 0];
end

bar_ylims = [ -14e-3, 6e-3 ];

freq_roi = 'beta';
freq_window = bands(freq_roi);

base_prefix = sprintf( '%s__%s', freq_roi, epoch );
base_subdir = sprintf( '%s%s', base_subdir, rev_t );

stats__proanti_coh( ...
    'is_z', false ...
  , 'is_cached', false ...
  , 'smooth_func', @(x) x ...
  , 'drug_type', 'nondrug_nanmedian' ...
  , 'is_pro_minus_anti', false ...
  , 'spectra', false ...
  , 'specificity', 'sites' ...
  , 'epochs', epoch ...
  , 'do_save', true ...
  , 'base_subdir', base_subdir ...
  , 'remove', rev_types(rev_t) ...
  , 'bar_mask_inputs', mask_inputs ...
  , 'base_prefix', base_prefix ...
  , 'time_window', t_window ...
  , 'freq_window', freq_window ...
  , 'bar_ylims', bar_ylims ...
  , 'line_ylims', [-0.02, 0.02] ...
  , 'spectral_time_window', [-350, 300] ...
  , 'spectral_freq_window', [0, 100] ...
  , 'spectral_clims', [-6.5e-3, 6.5e-3] ...
  , 'stretch_spectral_ylims', false ...
  , 'plot_bar', false ...
  , 'plot_lines', true ...
);

end

%%

rev_t = 'revB';
bands = dsp3.get_bands( 'map' );

for i = 2

mask_inputs = {@find, {'targon', 'cued'}, @find, {'targacq', 'choice'}};

bar_ylims = [ -14e-3, 6e-3 ];

freq_roi = 'beta';
freq_window = bands(freq_roi);

base_prefix = sprintf( '%s__%s', freq_roi, epoch );
base_subdir = sprintf( '%s2', rev_t );

stats__proanti_coh( ...
    'is_z', false ...
  , 'is_pro_minus_anti', true ...
  , 'spectra', true ...
  , 'specificity', 'sites' ...
  , 'epochs', {'targon', 'targacq'} ...
  , 'do_save', true ...
  , 'base_subdir', base_subdir ...
  , 'remove', rev_types(rev_t) ...
  , 'bar_mask_inputs', mask_inputs ...
  , 'base_prefix', base_prefix ...
  , 'time_window', t_window ...
  , 'freq_window', freq_window ...
  , 'bar_ylims', bar_ylims ...
);

end