corr_outs = dsp3_plot_correlated_sf_coh_by_anatomy( ...
    'correlation_type', 'spearman' ...
  , 'save_plots', false ...
);

%%

labs = corr_outs.corr_labels';

mask = fcat.mask( labs ...
  , @find, {'new_gamma', 'beta'} ...
);

min_p = min( corr_outs.corr_data(mask, 2) );
max_r = max( abs(corr_outs.corr_data(mask, 1)) );