function dsp3_save_summarized_psd()

summary_spec = { 'days', 'regions', 'channels', 'administration', 'outcomes', 'trialtypes', 'unit_uuid' };

psd_defaults = dsp3.make.defaults.psd();
psd_defaults.summary_spec = summary_spec;

dsp3.save_summarized_psd( 'targAcq-150-original-reference-method' ...
  , psd_defaults ...
  , 'is_parallel', true ...
  , 'overwrite', false ...
  , 'skip_existing', true ...
);

end