function dsp3_run_plot_bar_coherence_simple()

rev_types = dsp3.get_rev_types();
bands = dsp3.get_bands( 'map' );

rev_t = 'revB';
freq_roi_name = 'new_gamma';
base_subdir = 'redux';

freq_roi = bands(freq_roi_name);

base_subdir = sprintf( '%s%s', base_subdir, rev_t );
base_prefix = sprintf( 'bar__%s', freq_roi_name );

mask_inputs = { @findnot, {'targAcq', 'cued'}, @findnot, {'targOn', 'choice'} };

dsp3_plot_bar_coherence_simple( ...
      'epochs', {'targacq'} ...
    , 'is_cached', true ...
    , 'is_pro_minus_anti', false ...
    , 'mask_inputs', mask_inputs ...
    , 'base_prefix', base_prefix ...
    , 'base_subdir', base_subdir ...
    , 'freq_window', freq_roi ...
    , 'remove', rev_types(rev_t) ...
    , 'bar_ylims', [-7e-3, 3e-3] ...
);

end