summary_spec = { 'days', 'regions', 'channels', 'administration', 'outcomes', 'trialtypes', 'unit_uuid' };

coh_defaults = dsp3.make.defaults.summarized_coherence();
coh_defaults.summary_spec = summary_spec;

dsp3.save_summarized_sfcoherence( 'targAcq-150-original-reference-method' ...
  , coh_defaults ...
  , 'is_parallel', true ...
  , 'overwrite', false ...
  , 'skip_existing', true ...
);