function dsp3_run_plot_bar_coherence_simple()

rev_types = dsp3.get_rev_types();
bands = dsp3.get_bands( 'map' );

rev_t = 'orig';
freq_roi_name = 'new_gamma';
base_subdir = 'redux';

freq_roi = bands(freq_roi_name);

base_subdir = sprintf( '%s%s', base_subdir, rev_t );
base_prefix = sprintf( 'bar__%s', freq_roi_name );

mask_inputs = { @findnot, {'targacq', 'cued'}, @findnot, {'targon', 'choice'} };

dsp3_plot_bar_coherence_simple( ...
    'epochs', {'targacq', 'targon'} ...
  , 'is_cached', true ...
  , 'is_pro_minus_anti', true ...
  , 'mask_inputs', mask_inputs ...
  , 'base_prefix', base_prefix ...
  , 'base_subdir', base_subdir ...
  , 'freq_window', freq_roi ...
  , 'remove', rev_types(rev_t) ...
  , 'bar_ylims', [-0.018, 5e-3] ...
  , 'drug_type', 'nondrug_nanmedian' ...
);

end