conf = dsp3.config.load();

mats = shared_utils.io.findmat( dsp3.get_intermediate_dir('summarized_sfcoherence/first-look', conf) );

[coh, labels, freqs, t] = bfw.load_time_frequency_measure( mats ...
  , 'get_labels_func', @(x) x.labels ...
  , 'get_data_func', @(x) x.data ...
  , 'get_freqs_func', @(x) x.f ...
  , 'get_time_func', @(x) x.t ...
);

%%

do_smooth = true;
do_save = false;

if ( do_smooth )
  smooth_func = @(x) smoothdata( x, 'smoothingfactor', 0.5 );
  base_prefix = 'smoothed__';
else
  smooth_func = @(x) x;
  base_prefix = 'non-smoothed__';
end

dsp3_plot_iti_aligned_sfcoherence( 'coh', coh, 'labels', labels', 'freqs', freqs, 't', t ...
  , 'config', conf ...
  , 'do_save', do_save ...
  , 'line_smooth_func', smooth_func ...
  , 'prefix', base_prefix ...
  , 'per_trial_type', false ...
  , 'lines_over_freq', true ...
  , 'monkey_minus_bottle', false ...
);