do_smooth = true;

if ( do_smooth )
  smooth_func = @(x) smoothdata( x, 'smoothingfactor', 0.5 );
  base_prefix = 'smoothed__';
else
  smooth_func = @(x) x;
  base_prefix = 'non-smoothed__';
end

dsp3_plot_iti_aligned_sfcoherence( 'coh', coh, 'labels', labels', 'freqs', freqs, 't', t ...
  , 'do_save', true ...
  , 'line_smooth_func', smooth_func ...
  , 'prefix', base_prefix ...
  , 'per_trial_type', false ...
  , 'lines_over_freq', true ...
  , 'monkey_minus_bottle', false ...
);