rev_types = dsp3.get_rev_types();

base_prefix = 'one_block_post';

use_rev = 'revB';
epoch = 'targacq';

base_subdir = sprintf( '%s%s_%s', base_prefix, use_rev, epoch );

stats__proanti_coh( ...
    'do_save',            true ...
  , 'is_pro_minus_anti',  true ...
  , 'spectra',            true ...
  , 'epochs',             epoch ...
  , 'is_post_minus_pre',  true ...
  , 'drug_type',          'drug_wbd' ...
  , 'is_z',               false ...
  , 'remove',             rev_types(use_rev) ...
  , 'specificity',        'sites' ...
  , 'base_subdir',        base_subdir ...
  , 'xlims',              [0, 100] ...
  , 'time_window',        [-50, 50] ...
  , 'keep_n_blocks_post', 2 ...
);