dsp3.xcorr( ...
    'overwrite',            true ...
  , 'filt_func',            @dsp3.zpfilter ...
  , 'xcorr_scale_opt',      'none' ...
  , 'output_subdir',        'across' ...
  , 'shuffle',              false ...
  , 'per_trial',            false ...
  , 'across_trials_type',   'nondrug' ...
);