function funcs = descriptive_funcs()

%   DESCRIPTIVE_FUNCS -- Get default row-wise summary functions.
%
%     OUT:
%       - `funcs` (cell array of function_handle)

funcs = { ...
    @rows ...
  , @(x) mean(x, 1) ...
  , @(x) median(x, 1) ...
  , @(x) std(x, [], 1) ...
  , @plotlabeled.sem ...
};

end