function labs = get_unit_labels( unit, varargin )

shared_utils.assertions.assert__isa( unit, 'struct', 'the unit' );
shared_utils.assertions.assert__is_scalar( unit );


unit_rating = unit.rating;
unit_uuid = unit.unit_uuid;
channel_str = unit.channel_str;
region = unit.region;
day = unit.day;
session = unit.session;
mda_file = unit.mda_file;
pl2_file = unit.pl2_file;

labs = SparseLabels.create( ...
    'channel', channel_str ...
  , 'region', region ...
  , 'days', day ...
  , 'session_ids', session ...
  , 'unit_uuid', sprintf( 'unit_uuid__%d', unit_uuid ) ...
  , 'unit_rating', sprintf( 'unit_rating__%d', unit_rating ) ...
  , 'mda_file', mda_file ...
  , 'pl2_file', pl2_file ...
  , varargin{:} ...
);

end