function funcs = nandescriptive_funcs()

%   DESCRIPTIVE_FUNCS -- Get default row-wise summary functions, excluding nan
%
%     OUT:
%       - `funcs` (cell array of function_handle)

funcs = { ...
    @rows ...
  , @(x) nanmean(x, 1) ...
  , @(x) nanmedian(x, 1) ...
  , @(x) nanstd(x, [], 1) ...
  , @dsp3.nansem1d ...
};

end